// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmosvh74gKc7SzWOzdsEdYOn0_Mg5tE7Y',
    appId: '1:663259158617:web:92214eb176f83e03d27948',
    messagingSenderId: '663259158617',
    projectId: 'animal-c320d',
    authDomain: 'animal-c320d.firebaseapp.com',
    storageBucket: 'animal-c320d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkUNLbSqM12Mlmwn9MgVKD_IJcrk7kCJA',
    appId: '1:663259158617:android:8d09c2e3124a27b1d27948',
    messagingSenderId: '663259158617',
    projectId: 'animal-c320d',
    storageBucket: 'animal-c320d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgjk2yVo3mzr9eoxvH_S42t6etEXVebLY',
    appId: '1:663259158617:ios:82f144ed12a370b0d27948',
    messagingSenderId: '663259158617',
    projectId: 'animal-c320d',
    storageBucket: 'animal-c320d.appspot.com',
    iosBundleId: 'com.example.animalApp',
  );
}
